# Generated by Django 3.2.9 on 2021-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('directorate', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=50)),
                ('problem', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
